[package]
name    = "eunomia"
version = "0.1.0"
edition = "2021"

[lib]
name = "eunomia"
path = "src/lib.rs"

[features]
default = ["console-serial"]
console-serial = []

[dependencies]
libthemis = { path = "../themis/crates/libthemis" }
themis-abi = { path = "../themis/crates/themis-abi" }

[profile.dev]
panic = "abort"

[profile.release]
panic   = "abort"
opt-level = "s"
lto     = true
