name: Capability build and unit tests

on:
  push:
    branches: [ "v2026.1" ]
    paths:
      - '2026/*'
  pull_request:
    branches: [ "v2026.1" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./2026

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
